### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by polytypic** [ocaml-multicore/picos#84]
Next:

* [ ] Scheduler concept
* [ ] Structured concurrency library/sample/primitives
* [ ] io_uring based IO library

Soon:

* [ ] Lwt interop
* [ ] Async interop

Eventually:

* [ ] Sample JavaScript scheduler
* [ ] Synchronous channel
